### PR TITLE
Tech - Add Splash Screen blueprint

### PR DESCRIPTION
**Pull request by indie-rok**
Adds the first blue print, splash screen.

Logo can be changed by updating code or modifing the image

Screenshot 2019-06-28 at 19 00 07

### CODE REVIEW

**Comment by anandkulkarni** [comment]
1) Looks good, but why not use the official splash screen we have, which is a lot prettier?
2) Can we put a default app name on the splash screen?

**Comment by indie-rok** [comment]
Thanks for the review @anandkulkarni 
1) Do you mean the one from here? (from `react-native-firebase`) https://github.com/crowdbotics/react-native-firebase-scaffold/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/src/pages/Login/index.js

2) Sure we can!

**Comment by anandkulkarni** [comment]
I'm referring to these:
https://github.com/crowdbotics/react-native-frontend-scaffold

The frontends for most of our blueprints should just be copy/pasted from this app.

**Comment by indie-rok** [comment]
Closing for #18

**Pull request closed without merging**
